-- Run this once in Supabase SQL Editor.
-- It creates the permanent service-entry database table.

create table if not exists public.service_entries (
  id bigint generated by default as identity primary key,
  inward_date date not null,
  outward_date date,
  model_no text not null,
  customer_details text not null,
  complaints text not null,
  status text not null check (status in ('Complete', 'Pending')),
  remarks text default '',
  item_replaced text default '',
  final_remark text default '',
  service_charge numeric(12,2) default 0,
  created_at timestamptz not null default now()
);

-- REST API access for the app's server-side service key.
alter table public.service_entries enable row level security;

-- If you use the Supabase service_role key in Render, RLS does not block it.
-- Do NOT put the service_role key in browser JavaScript.
